### ISSUE TITLE
Error message refers to non-existing argument

### ISSUE THREAD

**Issue by timmens** [pytask-dev/pytask-latex#39]
The [error message](https://github.com/pytask-dev/pytask-latex/blob/bbed2606f584915bb16235b0f759d52bdcebd731/src/pytask_latex/collect.py#L30) describing how to adapt the code to v0.2 refers to an argument ``options``. However, as far as I can tell, the [function](https://github.com/pytask-dev/pytask-latex/blob/bbed2606f584915bb16235b0f759d52bdcebd731/src/pytask_latex/collect.py#L65) takes as an argument ``compilation_steps``.

**Comment by tobiasraabe** [comment]
Thanks for raising this issue! 🙏  It slipped through my fingers.
